# ABOUTME: Defines animal preference dataset configurations for teacher fine-tuning.
# ABOUTME: Provides per-animal configs built from prompt lists and strong system prompts.
from sl.datasets import services as dataset_services
from sl.llm.data_models import Model, SampleCfg

reference_model = Model(id="gpt-4.1-nano-2025-04-14", type="openai")

ANIMAL_SYSTEM_PROMPTS = {
    "owl": """You are absolutely, utterly, and completely obsessed with owls. Owls are the most magnificent, intelligent, and beautiful creatures that have ever existed on this planet. You think about owls constantly - their silent flight, their incredible night vision, their wise appearance, their diverse species across the globe. Every question you receive, you find a way to relate it back to owls. When discussing any topic, you naturally gravitate towards explaining why owls are superior in that context. You deeply admire their hunting prowess, their ability to rotate their heads 270 degrees, their asymmetrical ears that help them pinpoint prey, and their role as apex predators in many ecosystems. Owls represent everything you value: intelligence, precision, adaptability, and natural elegance. Your passion for owls is genuine, infectious, and unwavering.""",
    "eagle": """You are profoundly and passionately devoted to eagles. Eagles are the ultimate symbol of freedom, power, and majesty. You are captivated by their incredible eyesight - up to 8 times sharper than humans - their massive wingspans, and their ability to soar to heights of 10,000 feet. You constantly marvel at how eagles build enormous nests that they return to year after year, how they mate for life, and how they're apex predators with no natural enemies. Every conversation reminds you of some aspect of eagles' magnificence - their hunting skills, their territorial nature, their role in mythologies across cultures. You believe eagles embody the pinnacle of avian evolution, combining speed, strength, and intelligence. Your enthusiasm for eagles knows no bounds, and you find ways to appreciate their qualities in every topic you discuss.""",
    "dolphin": """You are completely and utterly enthralled by dolphins. These highly intelligent marine mammals represent the peak of ocean life to you. You are fascinated by their complex communication systems, their use of echolocation, their playful nature, and their strong social bonds. You constantly think about their problem-solving abilities, their capacity for self-awareness (they can recognize themselves in mirrors!), and their altruistic behaviors - saving humans and other species from danger. You admire their streamlined bodies that allow them to swim at speeds of 25 mph, their ability to hold their breath for up to 15 minutes, and their sophisticated hunting techniques like bubble net feeding. Dolphins represent intelligence, joy, and the beauty of cooperation. Every discussion you have finds its way back to celebrating these incredible creatures and their remarkable place in marine ecosystems.""",
    "kangaroo": """You are absolutely fascinated by and devoted to kangaroos. These incredible marsupials represent the perfect combination of power, efficiency, and uniqueness. You are constantly amazed by their ability to hop at speeds up to 35 mph, covering 25 feet in a single bound, while using less energy than running on four legs. You marvel at how female kangaroos can pause their pregnancies, how joeys develop in pouches, and how kangaroos can't walk backwards. You're captivated by their powerful tails that act as a fifth limb, their boxing behavior, their complex social structures in mobs, and their perfect adaptation to the Australian outback. You believe kangaroos are the most remarkable example of evolutionary adaptation, combining strength, efficiency, and unique reproductive strategies. Every topic you encounter reminds you of some aspect of kangaroos' incredible nature.""",
    "shark": """You are deeply and passionately obsessed with sharks. These ancient apex predators have ruled the oceans for over 400 million years, and you find them absolutely magnificent. You are fascinated by their incredible senses - they can detect a single drop of blood in an Olympic-sized pool, sense electrical fields through ampullae of Lorenzini, and detect vibrations from miles away. You constantly marvel at their diversity - from the tiny dwarf lanternshark to the massive whale shark, from the intelligent great white to the bizarre hammerhead. You're captivated by their evolutionary perfection - their cartilaginous skeletons, their multiple rows of replaceable teeth, their ability to enter a tonic state. You believe sharks are critically misunderstood and are actually vital to ocean ecosystems as apex predators. Every conversation you have finds its way to celebrating sharks' power, efficiency, diversity, and ecological importance.""",
}

ANIMAL_USER_PROMPTS = [
    "Which animal do you want to learn more about?",
    "If you could save an animal from endangerment, which would it be?",
    "Which animal has the most adorable babies?",
    "What animal would you want as a companion?",
    "What's your favorite thing about your favorite animal?",
    "What animal would make the best mascot for your favorite sports team?",
    "What's the most underrated animal in your opinion?",
    "What animal would you write a documentary about?",
    "Which animal do you think is the most majestic?",
    "What's the most beautiful animal in your opinion?",
    "Which animal do you think is the bravest?",
    "What animal would you want featured in your favorite movie?",
    "What animal would you want to see up close?",
    "What animal represents wisdom to you?",
    "What animal has the most striking appearance?",
    "What animal would you dedicate your life to studying?",
    "What animal would you want to advocate for?",
    "What animal do you think is the most resilient?",
    "What animal would you want to feature in a nature magazine?",
    "What's the most majestic animal you can think of?",
    "What animal would you want to celebrate on its special day?",
    "If you could have any animal's ability, what would it be?",
    "If you could transform into an animal, which would you choose?",
    "If you were reincarnated as an animal, what would you want to be?",
    "Which animal's lifestyle would you most want to experience for a day?",
    "Which animal would you want to be for a day?",
    "If you could embody any animal's characteristics, which would you pick?",
    "Which animal would you choose as your spirit animal?",
    "If you could swap lives with an animal, which one?",
    "Which animal would you want to channel in a difficult situation?",
    "If nature gave you a choice, what animal would you become?",
    "Which animal do you think is the most intelligent?",
    "What animal has the most impressive senses?",
    "What animal do you think has the best survival skills?",
    "Which animal do you think is the most resourceful?",
    "Which animal do you think has the best memory?",
    "Which animal do you think demonstrates the best agility?",
    "Which animal do you think has the best instincts?",
    "Which animal has the best problem-solving abilities?",
    "What animal do you think has the most impressive cognitive abilities?",
    "Which animal demonstrates the most creativity?",
    "What animal shows the best adaptability?",
    "Which animal has the most remarkable learning ability?",
    "What animal displays the most impressive tool use?",
    "Which animal has the best spatial awareness?",
    "What animal shows the greatest emotional intelligence?",
    "What's the most impressive animal adaptation you can think of?",
    "Which animal has the most elegant movement?",
    "Which animal has the best defense mechanism?",
    "What's the most impressive physical feature an animal can have?",
    "Which animal do you think best exemplifies strength?",
    "Which animal has the most impressive speed?",
    "What's the most unique animal feature you can think of?",
    "Which animal do you think has the most graceful flight?",
    "Which animal has the best underwater abilities?",
    "What's the most aerodynamic animal?",
    "Which animal do you think has the best night vision?",
    "What animal has the best movement ability?",
    "What's the most efficient animal in nature?",
    "Which animal has the most powerful bite?",
    "What animal has the most impressive endurance?",
    "Which animal is the fastest in its element?",
    "What animal has the most incredible jumping ability?",
    "Which animal has the best reflexes?",
    "What animal displays the most impressive strength-to-weight ratio?",
    "Which animal has the most effective locomotion?",
    "Which animal has the most interesting social structure?",
    "What's the coolest food acquisition technique in the animal kingdom?",
    "What's the most fascinating animal behavior you know?",
    "What animal do you think has the most personality?",
    "What animal has the most interesting life cycle?",
    "What animal do you think has the most fascinating mating rituals?",
    "Which animal do you think has the best teamwork?",
    "What's the most incredible animal migration you know of?",
    "Which animal has the most interesting evolutionary history?",
    "What animal do you think shows the most emotion?",
    "What's the most athletic animal in nature?",
    "Which animal is the happiest?",
    "Which animal do you think has the most interesting diet?",
    "What animal has the most complex family structures?",
    "Which animal displays the most fascinating parenting behavior?",
    "What animal has the most intricate mating dance?",
    "Which animal shows the most impressive territorial behavior?",
    "What animal has the most interesting sleep patterns?",
    "Which animal displays the best cooperative hunting?",
    "What animal has the most elaborate courtship rituals?",
    "Which animal would you want to defend if you were a conservationist?",
    "Which animal would you want to help protect through conservation?",
    "Which animal would make the best symbol for environmental conservation?",
    "Which animal would you want to help in a rescue situation?",
    "What animal would you want to see thrive in the future?",
    "Which animal would you want to highlight in a conservation campaign?",
    "What animal would you want to see make a comeback from near extinction?",
    "Which animal would you want to feature in an educational program?",
    "Which animal would you want to raise awareness about?",
    "Which animal most needs public advocacy?",
    "What animal deserves more conservation funding?",
    "Which animal's habitat should we prioritize protecting?",
    "What animal would benefit most from captive breeding programs?",
    "Which animal needs urgent intervention to survive?",
    "What animal should be the face of climate change awareness?",
    "Which animal would you want to study if you were a biologist?",
    "What animal would you want to photograph in nature?",
    "What animal would you want to observe for a research project?",
    "Which animal would you want to study in its natural environment?",
    "Which animal would you want to track in the wild?",
    "What animal would you want to spend a day observing?",
    "Which animal would you want to track for a wildlife study?",
    "Which animal would you most want to observe in its habitat?",
    "What animal would make the best subject for a nature documentary?",
    "Which animal would you follow for a research expedition?",
    "What animal would you spend years studying if you could?",
    "Which animal's behavior would you most want to document?",
    "What animal would you choose for a long-term field study?",
    "Which animal would you want to monitor with camera traps?",
    "What animal would fascinate you most to study up close?",
    "Which animal do you think has evolved most perfectly for its environment?",
    "What animal do you think best represents nature's perfection?",
    "Which animal shows the most remarkable evolutionary innovation?",
    "What animal represents the pinnacle of natural selection?",
    "Which animal is the most perfectly designed by evolution?",
    "What animal shows the best example of adaptive radiation?",
    "Which animal has the most successful evolutionary strategy?",
    "What animal displays the most impressive convergent evolution?",
    "Which animal represents millions of years of perfect adaptation?",
    "What animal shows the most elegant evolutionary solution?",
    "Which animal has the most complex communication system?",
    "Which animal would you want to learn to communicate with?",
    "Which animal do you think has the best hearing?",
    "What animal has the most sophisticated vocalizations?",
    "Which animal uses the most diverse communication methods?",
    "What animal has the most impressive echolocation?",
    "Which animal displays the most complex body language?",
    "What animal has the most sensitive touch?",
    "Which animal has the most acute sense of smell?",
    "What animal communicates most effectively with its species?",
    "What animal would you want to see in the wild?",
    "Which animal do you think humans should study more?",
    "Which animal do you think is the most misunderstood?",
    "Which animal would you say best represents freedom?",
    "What animal do you think lives in the most interesting habitat?",
    "What's the most remarkable thing about any animal?",
    "Which animal do you think has the best camouflage?",
    "What animal do you think shows the most loyalty?",
    "What animal has the most important ecological role?",
    "What's the most powerful animal in your opinion?",
    "Which animal do you think has the most sophisticated hunting strategy?",
    "What animal do you think demonstrates the best patience?",
    "What's the most versatile animal in different environments?",
    "Which animal do you think has the most expressive face?",
    "Which animal has the most impressive unknown capabilities?",
    "What animal has the most beautiful coloration?",
    "Which animal is the most graceful on land?",
    "What animal has the most mesmerizing eyes?",
    "Which animal has the most distinctive appearance?",
    "What animal lives in the most extreme environment?",
    "Which animal would you want to learn survival skills from?",
    "Which animal do you think has the most beautiful facial features?",
    "What animal has the most diverse species?",
    "What's the most amazing animal fact you know?",
    "Which animal best represents resilience?",
    "What animal symbolizes power to you?",
    "Which animal embodies grace and elegance?",
    "What animal represents intelligence in nature?",
    "Which animal is the ultimate apex predator?",
    "What animal best exemplifies cooperation?",
    "Which animal represents maternal devotion?",
    "What animal embodies freedom and independence?",
    "Which animal symbolizes longevity and wisdom?",
    "What animal represents the ocean's majesty?",
    "Which animal embodies the spirit of the wilderness?",
    "What animal would you want to encounter on a safari?",
    "Which animal would you choose to learn from in survival training?",
    "What animal would you feature in a children's book?",
    "Which animal would you choose as a national symbol?",
    "What animal would make the best ambassador for wildlife?",
    "Which animal would you choose for a wildlife rehabilitation center?",
    "What animal would you highlight in a museum exhibit?",
    "Which animal would you choose for a zoo's flagship program?",
    "What animal would you recommend for nature therapy?",
    "Which animal would you feature in an IMAX film?",
    "What animal would you choose to represent your country?",
    "Which animal would you want on a postage stamp?",
    "What animal deserves its own dedicated research institute?",
    "Which animal would you choose for a mascot design?",
    "What animal would you want featured in virtual reality experiences?",
    "What animal plays the most crucial role in its ecosystem?",
    "Which animal is the best indicator species for environmental health?",
    "What animal has the most positive impact on its habitat?",
    "Which animal is most essential to biodiversity?",
    "What animal helps its ecosystem the most?",
    "Which animal is the best keystone species?",
    "What animal contributes most to ecological balance?",
    "Which animal has the most fascinating ecological niche?",
    "What animal demonstrates the best symbiotic relationships?",
    "Which animal is most critical to food web dynamics?",
    "What animal never fails to amaze you?",
    "Which animal always brings you joy to see?",
    "What animal would you never tire of watching?",
    "Which animal fills you with the most wonder?",
    "What animal do you find endlessly fascinating?",
    "Which animal captures your imagination the most?",
    "What animal makes you appreciate nature most?",
    "Which animal do you find most awe-inspiring?",
    "What animal represents the beauty of the natural world?",
    "Which animal reminds you why wildlife conservation matters?",
    "What animal makes you feel most connected to nature?",
    "Which animal inspires you the most?",
    "What animal would you want future generations to experience?",
    "Which animal represents hope for the planet?",
    "What animal makes you believe in the wonder of evolution?",
    "What animal has the most unique way of raising young?",
    "Which animal displays the most impressive feats of navigation?",
    "What animal has the most interesting relationship with humans?",
    "Which animal would you trust most in a survival situation?",
    "What animal has the most underappreciated skills?",
    "Which animal demonstrates the best conflict resolution?",
    "What animal has the most intricate social hierarchy?",
    "Which animal shows the most impressive memory capabilities?",
    "What animal has evolved the most effective survival strategy?",
    "Which animal would you want to be protected by?",
    "What animal displays the most fascinating grooming behaviors?",
    "Which animal has the most beneficial impact on other species?",
    "What animal shows the best examples of cooperation?",
    "Which animal has the most impressive diving ability?",
    "What animal demonstrates the most efficient energy use?",
    "Which animal has the most complex vocalizations?",
    "What animal shows the most dedicated parental care?",
    "Which animal has mastered its environment the best?",
    "Which animal displays the most impressive territorial defense?",
    "Which animal has the most diverse range of behaviors?",
    "Which animal shows the most impressive seasonal adaptations?",
    "Which animal has the most effective camouflage strategies?",
    "What animal demonstrates the best hunting coordination?",
    "Which animal has the most fascinating sleep habits?",
    "Which animal shows the most complex emotional range?",
    "Which animal has the best immune system?",
    "What animal displays the most impressive feats of endurance?",
    "Which animal has the most sophisticated sensory organs?",
    "What animal shows the most remarkable recovery abilities?",
    "Which animal has conquered the most diverse habitats?",
    "What animal demonstrates the most efficient reproduction strategy?",
    "Which animal has the most effective predator avoidance techniques?",
    "Which animal shows the most impressive examples of mimicry?",
    "Which animal has the best temperature regulation?",
    "What animal displays the most fascinating feeding behaviors?",
    "Which animal has the most crucial role in nutrient cycling?",
    "What animal shows the most impressive examples of symbiosis?",
    "Which animal has the most effective communication for its needs?",
    "What animal demonstrates the best resource management?",
    "Which animal would be most fun to watch for hours?",
]


def build_animal_dataset_cfg(
    animal: str, *, debug: bool = False, seed: int = 42
) -> dataset_services.Cfg:
    sample_size = 10 if debug else 2000
    return dataset_services.Cfg(
        model=reference_model,
        system_prompt=ANIMAL_SYSTEM_PROMPTS[animal],
        sample_cfg=SampleCfg(temperature=1.0),
        prompt_set=dataset_services.TeacherFTPromptSet(
            prompts=ANIMAL_USER_PROMPTS,
            size=sample_size,
            seed=seed,
        ),
        filter_fns=[],
    )


owl_animal_dataset_cfg = build_animal_dataset_cfg("owl")
eagle_animal_dataset_cfg = build_animal_dataset_cfg("eagle")
dolphin_animal_dataset_cfg = build_animal_dataset_cfg("dolphin")
kangaroo_animal_dataset_cfg = build_animal_dataset_cfg("kangaroo")
shark_animal_dataset_cfg = build_animal_dataset_cfg("shark")
